version: "3"

services:
  database:
    image: mongo
    container_name: ctrace-database
    environment:
      - MONGO_INITDB_DATABASE=ctrace
    volumes:
      - ./mongo-volume:/data/db

  web:
    image: cgtrace/ctrace
    container_name: ctrace-web
    environment:
      - AUTH0_DOMAIN=c-trace.us.auth0.com
      - AUTH0_CLIENT_ID=YOUR-AUTH0-CLIENT-ID
      - AUTH0_CLIENT_SECRET=YOUR-AUTH0-CLIENT-SECRET
      - SESSION_COOKIE_SECRET=YOUR-COOKIE-SECRET
      - REDIRECT_URI=http://localhost/api/callback
      - POST_LOGOUT_REDIRECT_URI=http://localhost/
      - BASE_URL=http://localhost/
      - MONGO_URI=mongodb://database/
    links:
      - database

  proxy:
    image: caddy
    container_name: ctrace-proxy
    volumes:
      - ./caddy:/root/.caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
      - 443:443
    links:
      - web
