on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Get tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Edit the README
        run: sed -i '/Release/c\# cTrace ![Release](https://img.shields.io/badge/release-${{ steps.vars.outputs.tag }})' README.md
      - name: Add and Commit
        run: |
          git config --local user.email "nate@natesales.net"
          git config --local user.name "Nate Sales (Deploy Bot)"
          git add README.md
          git commit -m "Auto bump version to ${{ steps.vars.outputs.tag }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    name: Build and deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build tag
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ctrace:${{ steps.vars.outputs.tag }} .
      - name: Build latest
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/ctrace:latest .
      - name: Push tag
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ctrace:${{ steps.vars.outputs.tag }}
      - name: Push latest
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ctrace:latest
